# Generated by Django 5.0.7 on 2024-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=50)),
                ('Aurthor_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='books/')),
                ('available', models.BooleanField(default=True, help_text='1-default,0-false')),
            ],
        ),
    ]
